site_name: 画像生成wiki
site_url: https://katsuyuki-karasawa.github.io/GenerativeAI-wiki
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      accent: blue
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  language: ja
  font:
    text: IBM Plex Sans JP

  features:
    - header.autohide
    - search.suggest
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.action.edit
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
repo_name: GenerativeAI-wiki
repo_url: https://github.com/Katsuyuki-Karasawa/GenerativeAI-wiki

plugins:
  - offline
  - search:
      lang: ja
  - git-revision-date-localized:
      enabled: !ENV
      type: datetime
      enable_creation_date: true
      
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/Katsuyuki.Karasawa.io
      name: Facebook
      
    - icon: fontawesome/brands/github
      link: https://github.com/Katsuyuki-Karasawa
      name: GitHub
      
