site_name: 画像生成wiki
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  language: ja
  font:
    text: Kosugi Maru
  features:
    - header.autohide
    - search.share
    - search.suggest
    - navigation.tabs
    - navigation.top
    - content.code.copy
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
repo_url: https://github.com/Katsuyuki-Karasawa/GenerativeAI-wiki
repo_name: GenerativeAI-wiki

plugins:
  - search:
      lang: ja